spring:
  profile: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/easyhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root


























